### ISSUE TITLE
Incorrect Loading of Resources with '%20' in URL when using the ziplines ObjectStore

### ISSUE THREAD

**Issue by ARiedijk** [webrecorder/wabac.js#119]
When using the ziplines ObjectStore, the resources with '%20' in the URL are not being loaded correctly. The issue arises in the "**loadCDXFromIDX**" method, where the URL is converted to a surt (Sortable URI) and then passed through the "**decodeURIComponent**" method. Currently, the '%20' in the surt is converted to a space character. This causes a problem in the "**upperBound**" method, where the correct zipline rule is searched for. Due to the different sorting of '%20' and ' ' (space) characters, the result is incorrect.

Current code:
`const surt = this.waczfiles[waczname].useSurt ? decodeURIComponent(getSurt(url)) : url;`
Fix:
`const surt = this.waczfiles[waczname].useSurt ? getSurt(url) : url;`

Example: 
[indexes-testdata.zip](https://github.com/webrecorder/wabac.js/files/11665272/indexes-testdata.zip)
Given the secondary index "index.idx" and the following output files:

output1.txt: First 1024 lines
output2.txt: Next 1024 lines
output3.txt: Next 1024 lines
output4.txt: Next 1024 lines
output5.txt: Next 1024 lines
output6.txt: Next 1024 lines
When attempting to load a resource with the following URL:
`https://s3-eu-west-1.amazonaws.com/germanfrontdoorv4prod-live-1324fb6294be47ceb7851ec22521-174be63/Germany%20PI/Homepage%20Hero/PI_GER_Images/Start-pages/father_girl_seaside.jpg`
The current code would produce the following surt value:

`com,amazonaws,s3-eu-west-1)/germanfrontdoorv4prod-live-1324fb6294be47ceb7851ec22521-174be63/germany pi/homepage hero/esg_composing_sustainable_us_equity_fund_02_1200x535.jpg` 
**Note** that **germany pi/homepage hero/** should be **germany%20pi/homepage%20hero/**.

The current code also generates an incorrect upperBound value:
`com,amazonaws,s3-eu-west-1)/germanfrontdoorv4prod-live-1324fb6294be47ceb7851ec22521-174be63/germany pi/homepage hero/esg_composing_sustainable_us_equity_fund_02_1200x535.jpg 9999` 

This leads to loading the wrong index block, the 4th zipline row.
the values array has
`com,amazonaws,s3-eu-west-1)/germanfrontdoorv4prod-live-1324fb6294be47ceb7851ec22521-174be63/filer_public/cd/12/cd1292b4-0bc2-4870-8f30-b4a607cad439/termsde.json 20230603060401`

if we remove the **decodeURIComponent** method and just the plain surt with 9999 added we got:
`com,amazonaws,s3-eu-west-1)/germanfrontdoorv4prod-live-1324fb6294be47ceb7851ec22521-174be63/germany%20pi/homepage%20hero/esg_composing_sustainable_us_equity_fund_02_1200x535.jpg 9999`
and now do a upperBound search the value array has: the 6th zipline row
`com,amazonaws,s3-eu-west-1)/germanfrontdoorv4prod-live-1324fb6294be47ceb7851ec22521-174be63/germany%20pi/custom/quiz-tool_digitale_gesundheit/img/fil_quiz_grafik_ergebnis_platzhalter.png 20230604062214`
 This block contains the original search URL. I also made a small test tool to test the upperBound search.

[htmlindexdb.zip](https://github.com/webrecorder/wabac.js/files/11665497/htmlindexdb.zip)

**Comment by ikreymer** [comment]
Thanks for tracking this down - I see that I've added the decodeURIComponent in https://github.com/webrecorder/wabac.js/commit/c9f0f2f4adeb20e8a2dea945023d2f1d6bcfea34#diff-4464445ad026830014d045c2fd123c24b3c56fda9ba2425ba4931d5db6eecd0bR351
surely to fix something, but now can't remember what it was fixing specifically..

I thought perhaps the URLs were being stored in decoded form, but that is not the case for our tools...
Both Browsertrix Crawler and ArchiveWeb.page would keep the %20 in the URL, but I suppose some other tools could have URLs that are not properly %-encoded..

I wonder if it should try both, in case there is no match and the two are different..

**Comment by ARiedijk** [comment]
Since decodeURIComponent solves a problem, I think it's a good idea to try both as a fallback.
