### ISSUE TITLE
When a JavaScript is UTF-16 BE/LE encoded with or without a BOM (Byte Order Marker), the respective JavaScript is not processed. 

### ISSUE THREAD

**Issue by ARiedijk** [webrecorder/wabac.js#155]
When a JavaScript is UTF-16 BE/LE encoded with or without a BOM (Byte Order Marker), the respective JavaScript is not processed. 

The function parseLetConstGlobals(text) is not called because the async getText(isUTF8=false) function in response.js does not examine the read buffer to determine which encoding is applicable. The internal browser JavaScript parser does have this functionality. I have added an example Warc file.
[utf8-utf16-js-test.warc.gz](https://github.com/webrecorder/wabac.js/files/13947410/utf8-utf16-js-test.warc.gz)

**Comment by ikreymer** [comment]
Thanks for the repro sample! The PR in #160 should fix this, checking the BOM and applying the proper decoding for any text content.
