### ISSUE TITLE
Downloading as WARC converts 302 status to 200 status

### ISSUE THREAD

**Issue by austinfrey** [webrecorder/wabac.js#17]
I am using the webrecorder extension to archive a website. The site contains a 302 redirect which is correctly captured and functions correctly when using the extension's replay viewer. When downloading the WARC though, the status is converted from a `HTTP/1.1 302 Found` and written in the .warc file as `HTTP/1.1 200 OK`.  

The correct status is captured in the mimeStatusUrl index just not in the downloaded warc, so I am thinking something is getting lost in translation from the browser database to writing the warc but not exactly sure where.

(edit: maybe I should have posted in the extension repo but I am thinking the issue is in here somewhere)

**Comment by ikreymer** [comment]
Thanks for reporting! The download functionality is actually in this repo, so chances are it might be here as this is where the serialization happens: https://github.com/webrecorder/wabac.js/blob/main/src/downloader.js

The extension is still in alpha so there's things that may not work, but would be good to find this..
I haven't seen this particular issue before though and that sounds odd.. Maybe there was a redirect also, but only the 200 got written? Could you share the URL of the page where this happened?

**Comment by austinfrey** [comment]
Could a code sample help?

using express to setup the redirect, and the webrecorder extension to collect and download the pages.
```js
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.get('/redirect', (req, res) => {
  res.redirect('http://example.com')
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```

[this is the entry](https://gist.github.com/austinfrey/74859e7cc48530578c2cf73ce0827345#file-redirct-warc-L232) in the `.warc` file that I'm thinking should be a 302. The only change I made was to unzip the file.

**Comment by ikreymer** [comment]
Thanks! I found the issue! It was due to accidentally using a new version of warcio.js that I haven't released yet that accepts a single`statusline` param. Due to the param mismatch, it was just defaulting to `HTTP/1.1 200 OK` for all responses :(
Will fix!

**Comment by austinfrey** [comment]
@ikreymer This fix did the trick. Many thanks!!
