### ISSUE TITLE
[Feature]: Add back button to the "Archived Page Not Found" page

### ISSUE THREAD

**Issue by Shrinks99** [webrecorder/wabac.js#170]
### Context

Currently users can try opening the requested URL in a new tab, but this doesn't meet the needs of users who are using ReplayWeb.page without the full UI where a back button might be the best use case.

### What change would you like to see?

Add a back button in addition to the "open in new tab" option for easy navigation back to the previous page in every view.

**Comment by ikreymer** [comment]
Can just add a 'Back' link on the 404 page as a start.

**Comment by ikreymer** [comment]
<img width="933" alt="Screenshot 2024-05-30 at 4 30 14 PM" src="https://github.com/webrecorder/wabac.js/assets/1015759/d8dd4378-b844-43be-959d-e4255028b36f">

How does this look? Also added a check to only show the 'Go back' link if the page is a top-level page, to avoid showing it in iframes.
