### ISSUE TITLE
Support for loading Non-WARC Archives and API Integration

### ISSUE THREAD

**Issue by taclab** [webrecorder/wabac.js#186]
Hello,

At the Institut national de l'audiovisuel ([INA](https://netpreserve.org/about-us/members/ina-institut-national-de-laudiovisuel/)), we are interested in testing ReplayWeb.page to interact with our web archives. Our archives are not in WARC format and we use an in-house indexing system, so we are seeking a way to load them via wabac.js.
Do you have any suggestions on how to efficiently load them using wabac.js?

We have successfully replayed our archives with pywb using the [Memento API](https://pywb.readthedocs.io/en/latest/manual/memento.html).
Do you plan to integrate an API, support plugins or external APIs, like Memento, for example?

Thank you for all your hard work.

**Comment by ikreymer** [comment]
Hi @taclab, wabac.js is designed to be flexible and not necessarily tied to WARC or WACZ (there's also support for HAR and even experimental web bundle (WBN) support at one point). Support for an external CDX server + resource loading or Memento API like in pywb is definitely a possibility, and something that would be great to support. We just haven't had the time or resources to do that at the moment. Happy to discuss more with you, and perhaps something INA could help support and/or collaborate on?

**Comment by taclab** [comment]
Hi @ikreymer Thanks for your reply! I'll check with the INA team to see how we can work together. I'll get back to you. 
Thanks again.
