### ISSUE TITLE
Loading a collection already in the db, makes it crash

### ISSUE THREAD

**Issue by gregorymaertens** [webrecorder/wabac.js#33]
The latest commit added sourceUrl in the collAdded posted message:
 sourceUrl: res.config.sourceUrl
https://github.com/webrecorder/wabac.js/blob/199b90c53083415c9652f9475d453415a5088ab7/src/loaders.js#L325

However, when the collection is already in the db, res is set to 'true':
https://github.com/webrecorder/wabac.js/blob/199b90c53083415c9652f9475d453415a5088ab7/src/loaders.js#L301

It should instead return the db content, or something compatible with .config

**Comment by ikreymer** [comment]
Thanks for finding it, will have a fix soon!
Just curious, are you using wabac.js with replayweb.page, or separately? I think this condition is rarely hit with replayweb.page, so probably missed it for that reason, but can in other configurations.

**Comment by gregorymaertens** [comment]
thanks for the quick fix! No I'm using it outside replayweb.page, directly from https://unpkg.com/. When is the dist pushed to it?

**Comment by ikreymer** [comment]
1.4.5 has now been published
