### ISSUE TITLE
weird behavior when using an archive from https://www.bestbuy.com/

### ISSUE THREAD

**Issue by gregorymaertens** [webrecorder/wabac.js#36]
when making an archive from https://www.bestbuy.com/ (attached, rename it in .wacz) using the chrome extension 
[bestbuy.gz](https://github.com/webrecorder/wabac.js/files/6571145/bestbuy.gz, when played back with replayweb.page it behaves strangely: it renders the page fine at first then after a few seconds, it looks like it reloads the page and shows the navigation bar from replayweb (see screenshot
![Screen Shot 2021-05-31 at 17 23 31](https://user-images.githubusercontent.com/1636112/120214645-0d78ae00-c235-11eb-80ed-32d32bbd0a29.png)
 attached)

I didn't investigate the problem aside looking at the console logs (a lot of errors).

**Comment by ikreymer** [comment]
Should be fixed via c60f64b5cc7b1e6ce1e1d919d1d6ff70d51fc89a, will be in next release archiveweb.page/replayweb.page

**Comment by ikreymer** [comment]
Fixed!
