### ISSUE TITLE
Support for chunk encoded responses needed (was: replay not working)

### ISSUE THREAD

**Issue by luda171** [webrecorder/wabac.js#6]
Hello,
I read you recent excellent blog at DSHR's and think it is very promising development.
I tried to replay warcs produced by Warcprox using static https://wab.ac/  page by loading warc file. I tested many examples and it is not working (chrome on mac). The content-encoding (if I look inside warc response headers) is gzip . The test warc you provided is loading ok.    
![image](https://user-images.githubusercontent.com/7840283/66157288-b4302580-e5e0-11e9-800d-6e73f3768e17.png)
It is also not displaying list of urls. So maybe problem in indexing as well. Do you know what the problem is? Thanks Luda

**Comment by ikreymer** [comment]
Hi Luda,
Thanks for the bug report! Yes, definitely seems that the gzip decoding is failing for some reason... Would you be able to share the WARCs or a WARC record to test by any chance?

For the page list, that currently only works with WARCs created by Webrecorder, as they have special metadata that includes page list. There is not yet a page detection heuristic, but something that could be added.
(Should emphasize more that this is still a prototype)

**Comment by luda171** [comment]
[WARCPROX-20190911185156296-00000-8qlwtu4c.warc.zip](https://github.com/webrecorder/wabac.js/files/3688026/WARCPROX-20190911185156296-00000-8qlwtu4c.warc.zip)

**Comment by luda171** [comment]
I posted warc via github .

https://www.slideshare.net/martinklein0815/the-memento-tracer-framework-balancing-quality-and-scalability-for-web-archiving
Attachments area

**Comment by ikreymer** [comment]
Thanks! it's due to `Transfer-Encoding: chunked`, warcprox preserves chunking, and wabac.js is not currently de-chunking the content. Will work on fix!

**Comment by ikreymer** [comment]
Added chunked decoding, this WARC should now be fixed!

(Can't link to the attachment directly as no CORS added by github)

Also, it turns out page detection *was* there, but wasn't working.. Should work now and list the html pages in the WARC if none specified in warcinfo metadata.

**Comment by luda171** [comment]
thanks! it is working now.
