### ISSUE TITLE
warc2zim support broken

### ISSUE THREAD

**Issue by rgaudin** [webrecorder/wabac.js#69]
warc2zim currently uses wabac.js `2.9.6`. I tried to blindly update to the latest `2.11.1` release but then the homepage is not found anymore

<img width="795" alt="Screen Shot 2022-06-14 at 12 09 22" src="https://user-images.githubusercontent.com/57929/173573793-70d9eff5-d54e-4126-95b5-1ee444f50d47.png">

This is using WARCs from `https://irp.fas.org/doddir/milmed/index.html`

**Comment by edsu** [comment]
Where is warc2zim?

**Comment by rgaudin** [comment]
https://github.com/openzim/warc2zim

**Comment by ikreymer** [comment]
@rgaudin thanks, should be fixed on latest commit on 2.12-work branch

**Comment by rgaudin** [comment]
Thanks! I confirm it's fixed with that branch ATM. Please ping me once you release it so we can use it. Is there a way to get notified automatically?

**Comment by ikreymer** [comment]
Usually, replayweb.page has user-facing releases, but since you're using wabac.js directly, can also start doing GH releases here.
